import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Script id="react" src="https://unpkg.com/react@18/umd/react.development.js" ></Script> */}
        <Script id="react" src="https://unpkg.com/react@18/umd/react.development.js" strategy='beforeInteractive'></Script>
        {children}
      </body>
    </html>
  )
}
